apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: gitops-flux-workshop
  namespace: flux-system
spec:
  interval: 1m
  url: https://github.com/mtumilowicz/gitops-flux-workshop.git
  ref:
    branch: main
