apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: flux-system

secretGenerator:
  - name: sops-age
    files:
      - identity.agekey=workshop.agekey

generatorOptions:
  disableNameSuffixHash: true
