apiVersion: v1
kind: Secret
metadata:
    name: nginx-workshop-secret
type: Opaque
stringData:
    environment: ENC[AES256_GCM,data:O6wgOg==,iv:m6A4GfADgSMZoL7MVo0kWnRAryQ/9BHLEYiCxew/yGE=,tag:dfZeb2D9JxB5IXLPash99g==,type:str]
    token: ENC[AES256_GCM,data:ZOOBxbCA+FepemeaZNw9dfSq+Q==,iv:xNbz9mOnF2NOE3v4hhgTbOhpHMg3Y9O3LrtayW7Pbxg=,tag:4gyix7f/S8vEPjJq2mxPOw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzK2diaDRqL0kxSHM2WEJT
            QjNySi9UYmhKRTNwV2M2R0QxeEM5WjBhVVY0CmVaZjdrYzNwNzViYm40TjA5TWt3
            eFA2M2RORndmbHFEN0lrMnNLUEY0OTAKLS0tIDNCNTZrODl6N0FxdmlFTmJEVHBx
            clNzamFBM1AwalIxMUxvTXRMdUxRWGsK1jD88ZvFV9SZWAUhW7k62VnGVrZYhhgM
            2ijDuZiaIfYXq1SD4zRN+SGEmRrSo4b0Qv5iBBxTJHs7cOpX2CHqeQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1v4cpxtz052v63vnd6qkq323mpc0hhl525quled8zkjp7xjea7d3qvv5rml
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-12T19:51:51Z"
    mac: ENC[AES256_GCM,data:WB50iYbw5Gmy8uL33/dgH3wqjtTdiEECmqe7HFdqa1FRty7VelwepjUmgTzNlcucMGkbnRSeX3nbr5HgMSdY/qgBHZaW4/8hXKSk1QOwJZZ/yb+/wz9+l8fHqFJjF3B+6zoa8oWa8I6BLhT/FKYGr+VDIXOB5pkxEtpw/QKlIEQ=,iv:hlTCXrJwcvV8Ys6lpbTX7/VhYGXVftKFy0NVEr/GV7k=,tag:7Wzx6dfwfdtn+EgrnAFpkg==,type:str]
    version: 3.13.3
